# TiKV Importer configuration file template

# log file.
log-file = ""
# log level: trace, debug, info, warn, error, off.
log-level = "info"

# listening address of the status server
# status-server-address = "0.0.0.0:8286"

[server]
# set listening address.
addr = "0.0.0.0:8287"
# size of thread pool for grpc server.
grpc-concurrency = 16

[rocksdb]
# the maximum number of concurrent background jobs.
max-background-jobs = 32

[rocksdb.defaultcf]
# amount of data to build up in memory before flushing to disk.
write-buffer-size = "1GB"

# the maximum number of write buffers that are built up in memory.
max-write-buffer-number = 8

# the compression algorithms using in different levels.
# the algorithm at level-0 is using to compress KV data.
# the algorithm at level-6 is using to compress SST files.
# the algorithms at level-1 ~ level-5 are not used for now.
compression-per-level = ["lz4", "no", "no", "no", "no", "no", "lz4"]

[rocksdb.writecf]
compression-per-level = ["lz4", "no", "no", "no", "no", "no", "lz4"]

[security]
## The path for TLS certificates. Empty string means disabling secure connections.
# ca-path = ""
# cert-path = ""
# key-path = ""
# cert-allowed-cn = []

[import]
# the directory to store importing kv data.
import-dir = "/tmp/tikv/import"
# number of threads to handle RPC requests.
num-threads = 16
# number of concurrent import jobs.
num-import-jobs = 24
# maximum duration to prepare regions.
# max-prepare-duration = "5m"
# split regions into this size according to the importing data.
# region-split-size = "512MB"
# stream channel window size, stream will be blocked on channel full.
# stream-channel-window = 128
# maximum number of open engines
max-open-engines = 8
# speed limit of uploading SST to TiKV (unit: byte/s)
upload-speed-limit = "512MB"
# minimum ratio of target store available space: store_available_space / store_capacity
# Importer will pause to upload SST to target store if its available ratio less than
# this value, and give the store some time window to balance regions.
min-available-ratio = 0.05
